//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int WordID { get; set; }
        public string Word1 { get; set; }
        public string WordDef1 { get; set; }
        public string WordDef2 { get; set; }
        public string WordDef3 { get; set; }
        public string WordType { get; set; }
    }
}
